
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhaskar
 */
public class Update extends javax.swing.JFrame {

    LogicManager myLogicManager;
    String old = "";
    DefaultTableModel model;

    JLabel getEnterMobNoLabel() {
        return enterMobNoLabel;
    }

    JButton getSearchButton() {
        return searchButton;
    }

    JTextField getaName() {
        return name;
    }

    JTextField getMobno() {
        return mobno1;
    }

    JTextField getDob() {
        return dob;
    }

    JTextField getEmail() {
        return email;
    }

    JTextField getAddress() {
        return address;
    }

    JTextField getMobnoSearched() {
        return mobno;
    }

    public Update(LogicManager obj) {
        initComponents();
        myLogicManager = obj;
        this.setTitle("Update Contact");
        Container con = this.getContentPane();
        con.setBackground(new java.awt.Color(255, 187, 85));
        this.setLocationRelativeTo(null);
        searchButton.setContentAreaFilled(false);
        searchButton.setOpaque(true);
        searchButton.setBackground(new java.awt.Color(79, 223, 103));
        update.setContentAreaFilled(false);
        update.setOpaque(true);
        update.setBackground(new java.awt.Color(49, 203, 225));
        returnbtn.setContentAreaFilled(false);
        returnbtn.setOpaque(true);
        returnbtn.setBackground(Color.RED);
        goback.setContentAreaFilled(false);
        goback.setOpaque(true);
        goback.setBackground(Color.RED);
        update.setVisible(false);
        nameLabel.setVisible(false);
        name.setVisible(false);
        mobnoLabel.setVisible(false);
        mobno1.setVisible(false);
        emailLabel.setVisible(false);
        email.setVisible(false);
        dobLabel.setVisible(false);
        dob.setVisible(false);
        addressLabel.setVisible(false);
        address.setVisible(false);
        returnbtn.setVisible(false);
        this.setSize(488, 100); //[488, 60
        this.setTitle("Search");
        this.setIconImage(new ImageIcon(getClass().getResource("contacts.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterMobNoLabel = new javax.swing.JLabel();
        mobno = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        update = new javax.swing.JButton();
        dobLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mobno1 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        mobnoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        returnbtn = new javax.swing.JButton();
        goback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        enterMobNoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterMobNoLabel.setText("Enter the mobile number : ");

        mobno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobnoActionPerformed(evt);
            }
        });
        mobno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobnoKeyTyped(evt);
            }
        });

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dobLabel.setText(" Date of Birth (yyyy/mm/dd)");

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressLabel.setText("Address");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        mobno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobno1ActionPerformed(evt);
            }
        });
        mobno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobno1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobno1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobno1KeyTyped(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLabel.setText("Name");

        mobnoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mobnoLabel.setText("Mobile Number");

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailLabel.setText("Email ID");

        returnbtn.setText("GO BACK");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });

        goback.setText("BACK");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mobnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterMobNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(mobno1)
                            .addComponent(email)
                            .addComponent(address)
                            .addComponent(dob)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mobno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mobno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(enterMobNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mobnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mobno1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /* JComboBox<String> getyyyy(){
    return yyyy;
}
    JComboBox<String> getdd(){
        return dd;
    }
    JComboBox<String> getmm(){
        return mm;
    }*/
    private void mobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobnoActionPerformed

     }//GEN-LAST:event_mobnoActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String mo = getMobnoSearched().getText();
        if (mo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mobile number needed!");
        } else {
            old = mo;
            int ret = myLogicManager.search(this, mo);
            System.out.println(ret);
            if (ret == 1) {
                update.setVisible(true);
                nameLabel.setVisible(true);
                name.setVisible(true);
                mobnoLabel.setVisible(true);
                mobno1.setVisible(true);
                emailLabel.setVisible(true);
                email.setVisible(true);
                dobLabel.setVisible(true);
                dob.setVisible(true);
                addressLabel.setVisible(true);
                address.setVisible(true);
                returnbtn.setVisible(true);
                this.setSize(510, 319);
                goback.setVisible(false);
                this.setTitle("Update");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {

            String nm = name.getText().trim();
            String mo = mobno1.getText().trim();
            String adr = address.getText().trim();
            String db = dob.getText().trim();
            String[] arr = db.split("-");
            DateFormat df = new SimpleDateFormat("yyyy-mm-dd");
            Date checkdate;
            checkdate = df.parse(db);
            Calendar cal = Calendar.getInstance();
            cal.setLenient(false);
            cal.setTime(checkdate);
            cal.getTime();
            if (db.matches("\\d{4}-\\d{2}-\\d{2}")) {

                String em = this.getEmail().getText().trim();
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/iem", "root", "root");
                Statement stmt = con.createStatement();
                int bp = JOptionPane.showConfirmDialog(this, "Do you want to update the record ?");
                if (bp == JOptionPane.YES_OPTION) {
                    String query = "update contact set name = '" + nm + "', number = '" + mo + "', address = '" + adr + "', DOB = '" + db + "', email = '" + em + "'where number = '" + old + "';";
                    System.out.println(query);
                    boolean i = stmt.execute(query);
                    System.out.println(i);
                    JOptionPane.showMessageDialog(this, "Record has been updated");
                }
                if (bp == JOptionPane.CANCEL_OPTION) {
                    this.dispose();
                    new ContactList().setVisible(true);
                }
                if (bp == JOptionPane.NO_OPTION) {
                    this.dispose();
                    this.setVisible(true);
                }
                stmt.close();
                con.close();
            }

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Date not in correct format");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid Date");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error in connectivity");
        }

    }//GEN-LAST:event_updateActionPerformed

    private void mobno1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobno1KeyTyped
        myLogicManager.checkDigits(mobno1, this);
    }//GEN-LAST:event_mobno1KeyTyped

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void mobno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobno1ActionPerformed

    private void mobnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoKeyTyped

    }//GEN-LAST:event_mobnoKeyTyped

    private void mobno1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobno1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_mobno1KeyPressed

    private void mobnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobnoKeyPressed

    private void mobnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoKeyReleased
        // TODO add your handling code here:
        myLogicManager.checkDigits(mobno, this);
    }//GEN-LAST:event_mobnoKeyReleased

    private void mobno1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobno1KeyReleased
        myLogicManager.checkDigits(mobno1, this);         // TODO add your handling code here:
    }//GEN-LAST:event_mobno1KeyReleased

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        this.dispose();
        Update obj = new Update(myLogicManager);
        obj.setVisible(true);
    }//GEN-LAST:event_returnbtnActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        this.dispose();
        new ContactList().setVisible(true);
    }//GEN-LAST:event_gobackActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel enterMobNoLabel;
    private javax.swing.JButton goback;
    private javax.swing.JTextField mobno;
    private javax.swing.JTextField mobno1;
    private javax.swing.JLabel mobnoLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton returnbtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
